kind: pipeline
name: nodeapp
steps:
  - name: build
    image: node:latest
    commands:
      - npm install

  - name: publish
    image: plugins/gcr
    tag: ${DRONE_COMMIT}
    settings:
      repo: gcr.io/project-one-266117/nodeapp
      json_key:
        from_secret: google_credentials

  - name: deploy
    image: nytimes/drone-gke
    expand_env_vars: true
    verbose: true
    vars:
      image: gcr.io/project-one-266117/nodeapp:${DRONE_COMMIT}
      app: nodeapp
      env: dev
      user: root
    zone: us-east1-b
    verbose: true
    cluster: mykubecluster
    project: project-one-266117
    token:
      from_secret: google_credentials


trigger:
  branch:
    - test_branch
  event:
    include:
    - push

