kind: pipeline
name: nodeapp
steps:
  - name: build
    image: node:latest
    commands:
      - npm install

  - name: publish
    image: plugins/gcr
    tag: ${DRONE_COMMIT}
    settings:
      repo: gcr.io/project-one-266117/nodeapp
      json_key:
        from_secret: google_credentials

  - name: deploy
    image: nytimes/drone-gke
    expand_env_vars: true
    environment:
      TOKEN:
        from_secret: google_credentials
      PLUGIN_ZONE: us-east1-b
      PLUGIN_VERBOSE: true
      PLUGIN_CLUSTER: mykubecluster
      PLUGIN_PROJECT: project-one-266117
      PLUGIN_VARS: '{"app": "nodeapp","env": "dev","image": "gcr.io/project-one-266117/nodeapp:${DRONE_COMMIT}","user": "root"}'

trigger:
  branch:
    - test_branch
  event:
    include:
    - push

